// Visually displays a set of integers being sorted by popular sorting algorithms in real time. 
// Author: Dylan - last updated 9/17/21

/**
 * List of functionalities that need to included:
 * 
 * Start, stop, & clear buttons
 * Text collection - user chooses number of randomly generated integers to sort
 * JPanel for buttons and text collection on the bottom of the JFrame
 * JPanel to display the sorting on the main upper bulk of the JFrame
 * Algorithm buttons
 * 
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class DisplayMain extends JFrame{

	/**
	 * Default Serial ID for JFrames.
	 */
	private static final long serialVersionUID = 1L;

	// ???

	// JPanels
	/**
	 * JPanel that houses the sub-JPanels, which contain all of the buttons. Sits at
	 * the bottom of the JFrame.
	 */
	private JPanel buttonsMasterPanel;

	/**
	 * JPanel on which the sorting is displayed.
	 */
	private JPanel sortingPanel;

	/**
	 * JPanel that houses the start/stop and clear buttons. Nested in
	 * buttonsMasterPanel. Sits to the left on the bottom of the JFrame.
	 */
	private JPanel leftButtonsPanel;

	/**
	 * JPanel that houses the input collection. Nested in buttonsMasterPanel. Sits
	 * on the center of the bottom of the JFrame.
	 */
	private JPanel centerButtonsPanel;

	/**
	 * JPanel that houses the algorithm buttons. Nested in buttonsMasterPanel. Sits
	 * on the right of the bottom of the JFrame.
	 */
	private JPanel rightButtonsPanel;

	// JButtons
	/**
	 * JButton that starts/stops the chosen sorting algorithm.
	 */
	private JButton startStopButton;

	/**
	 * JButton for selecting bubble sort.
	 */
	private JButton mergeSortButton;

	/**
	 * JButton for selecting bubble sort.
	 */
	private JButton quickSortButton;

	/**
	 * JButton for selecting bubble sort.
	 */
	private JButton radixSortButton;

	/**
	 * JButton for selecting bubble sort.
	 */
	private JButton heapSortButton;

	/**
	 * JButton for selecting bubble sort.
	 */
	private JButton bubbleSortButton;
	
	/**
	 * JButton for randomizing values to be sorted.
	 */
	private JButton randomizeButton;

	/**
	 * Generates an array of random integers between 1 and 1200.
	 */
	private NumberGenerator ng;
	
	// Array of integers generated by NumberGenerator to be sorted by chosen algorithm. 
	private int[] intsToBeSorted;

	/**
	 * Private constructor for this class.
	 */
	private DisplayMain() {
		setup();
	}

	/**
	 * TODO!!!
	 */
	private void setup() {
		/**
		 * Setup parameters such as exiting behavior, size of the JFrame, visibility of
		 * the JFrame, and the layout.
		 */
		this.setTitle("Sorting Algorithm Visualizer");
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setExtendedState(MAXIMIZED_BOTH);
		this.setLayout(new BorderLayout());

		// Instantiate JPanels.
		sortingPanel = new JPanel();
		buttonsMasterPanel = new JPanel();
		leftButtonsPanel = new JPanel();
		centerButtonsPanel = new JPanel();
		rightButtonsPanel = new JPanel();

		/**
		 * Set the layouts of all JPanels and nests the left, center, and right JPanels
		 * in the buttonsMasterPanel.
		 */
		buttonsMasterPanel.setLayout(new BorderLayout());
		leftButtonsPanel.setLayout(new FlowLayout());
		centerButtonsPanel.setLayout(new FlowLayout());
		rightButtonsPanel.setLayout(new FlowLayout());
		buttonsMasterPanel.add(leftButtonsPanel, BorderLayout.WEST);
		buttonsMasterPanel.add(centerButtonsPanel, BorderLayout.CENTER);
		buttonsMasterPanel.add(rightButtonsPanel, BorderLayout.EAST);

		// Set background colors of the JPanels.
		sortingPanel.setBackground(Color.DARK_GRAY);
		rightButtonsPanel.setBackground(Color.yellow);
		centerButtonsPanel.setBackground(Color.yellow);
		leftButtonsPanel.setBackground(Color.yellow);

		// Instantiate JButtons & add actions listeners to them.
		startStopButton = new JButton("          Start           ");
		mergeSortButton = new JButton("Merge Sort");
		radixSortButton = new JButton("Radix Sort");
		heapSortButton = new JButton("Heap Sort");
		quickSortButton = new JButton("Quick Sort");
		bubbleSortButton = new JButton("Bubble Sort");
		randomizeButton = new JButton("Get New Values");
		startStopButton.addActionListener(new StartStopListener());
		mergeSortButton.addActionListener(new MergeSortListener());
		radixSortButton.addActionListener(new RadixSortListener());
		heapSortButton.addActionListener(new HeapSortListener());
		quickSortButton.addActionListener(new QuickSortListener());
		bubbleSortButton.addActionListener(new BubbleSortListener());
		randomizeButton.addActionListener(new RandomizeListener());

		

		

		// Add JButtons to rightButtonsPanel JPanel.
		rightButtonsPanel.add(randomizeButton);
		rightButtonsPanel.add(startStopButton);

		// Add JButtons to leftButtonsPanel JPanel.
		leftButtonsPanel.add(bubbleSortButton);
		leftButtonsPanel.add(mergeSortButton);
		leftButtonsPanel.add(radixSortButton);
		leftButtonsPanel.add(heapSortButton);
		leftButtonsPanel.add(quickSortButton);


		// Add main JPanels to JFrame.
		this.add(sortingPanel, BorderLayout.CENTER);
		this.add(buttonsMasterPanel, BorderLayout.SOUTH);
		
		// Instantiate NumberGenerator.
		ng = new NumberGenerator();

		// Set JFrame as visible.
		this.setVisible(true);
		
		// Obtain the array of integers to be sorted. 
		intsToBeSorted = ng.getRandomArray(368);
		

	}
	
	

	@Override
	public void paint(Graphics g) {
		super.paint(g);
		int x = 40;
		if (intsToBeSorted != null) {
			for (int i = 0; i < intsToBeSorted.length; i++) {
				g.fillRect(x, 765 - intsToBeSorted[i], 3, intsToBeSorted[i]);
				x += 4;
			}
		}
		
	}
	
	// Action Listeners.
	
	// Action listener for the startStop button.
	private class StartStopListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {
		}

	}

	// Action listener for the bubbleSort button.
	private class BubbleSortListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

		}

	}

	// Action listener for the mergeSort button.
	private class MergeSortListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

		}

	}

	// Action listener for the heapSort button.
	private class HeapSortListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

		}

	}

	// Action listener for the quickSort button.
	private class QuickSortListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

		}

	}

	// Action listener for the radixSort button.
	private class RadixSortListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {

		}

	}


	// Action listener for the JTextField.
	private class RandomizeListener implements ActionListener {

		@Override
		public void actionPerformed(ActionEvent e) {
			intsToBeSorted = ng.getRandomArray(368);
			repaint();
		}
	}

	/**
	 * TODO!!!
	 * 
	 * @param args
	 */
	public static void main(final String[] theArgs) {
		DisplayMain dm = new DisplayMain();
	}
}
